#!/usr/bin/env bash

files_list=$(ls)
files=0
for file in $files_list:
do
	if [ "$file" != "git_push" ]
	then
		files=$((files + 1))
		git add "$file"
		git commit -m "$file"
		git push
	fi
done
echo "Total commited: $files files"

#To take care of deleted and hidden files:

"""
git add .
git commit -m "New comm"
git push
"""
